name: Projeto digital

on:
  push:
    branches:
      - main
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Teste
        run: echo "Projeto funcionando"

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Deploy

        run: |

          echo "DB_HOST=${{ secrets.PROD_DB_HOST }}"
          echo "DB_USER=${{ secrets.PROD_DB_USER }}"
          echo "DB_PASSWORD=***MASKED***"
          echo "Deploy OK"